---
version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build_docs:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: docs/requirements.txt
      - run:
          name: Build docs
          command: make -C docs html
      - persist_to_workspace:
          root: docs/_build/html
          paths: .
      - store_artifacts:
          path: docs/_build/html/

workflows:
  main:
    jobs:
      - build_docs
