---
version: 2.1

orbs:
  python: circleci/python@1.2.1

jobs:
  build_docs:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip-dist
          pip-dependency-file: docs/requirements.txt
      - run:
          name: Build docs
          command: make -C docs html
      - persist_to_workspace:
          root: docs/_build/html
          paths: .
      - store_artifacts:
          path: docs/_build/html/

  deploy:
    docker:
      - image: "node:8.10.0"
    steps:
      - attach_workspace:
          at: html
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "MatplotlibCircleBot@nomail"
            git config user.name "MatplotlibCircleBot"
      - add_ssh_keys:
          fingerprints:
            - "25:2e:77:93:7e:0e:af:77:b0:be:e7:fe:86:2c:5b:96"
      - run:
          name: "Deploy new docs"
          command: |
            touch html/.nojekyll  # Disable jekyll builds on GitHub.
            gh-pages \
              --dotfiles \
              --message "[skip ci] Doc build of $CIRCLE_SHA1" \
              --dist html

workflows:
  main:
    jobs:
      - build_docs
      - deploy:
          requires:
            - build_docs
          filters:
            branches:
              only: main
