---
name: "CircleCI artifact handling"
on: [status]
jobs:
  circleci_artifacts_redirector_job:
    if: "${{ github.event.context == 'ci/circleci: build_docs' }}"
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-path: 0/docs/_build/html/index.html
          circleci-jobs: build_docs
          job-title: View the built docs
