name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Make docs builds
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html